Changes to be committed: 	modified:   App/config.py 	modified:   App/models/author_publication.py 	modified:   App/models/user.py
    Start of testing with code, trying to fix
    SyntaxError: positional argument follows keyword argument
    on line 13 of author_publication
    because of
    db.Column("auth_no", db.Integer)